apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: expense-046
  region: us-east-1 
managedNodeGroups:
 - name: expense
   instanceType: m5.large
   desiredCapacity: 3 
   spot: true

# one eks control plane and create 3 nodes  and connect to it